[package]
name = "tipsy"
version = "0.1.0"
edition = "2024"

[dependencies]
swc_atoms = "^5.0.0"
swc_common = "^8.0.0"
swc_ecma_ast = "^8.0.0"
swc_ecma_compat_es2015 = "^11.0.0"
swc_ecma_minifier = "^12.0.0"
swc_ecma_transforms_base = "^11.0.0"
swc_ecma_utils = "^11.0.0"
swc_ecma_visit = "^8.0.0"
swc_bundler = "^11.0.0"
swc_ecma_loader = "^8.0.0"
swc_ecma_parser = "^10.0.0"